guest/urls.py
from django.conf.urls import url
from guest import views
from django.contrib.auth import views as auth_views
# from guest.payment_views import payment,response

urlpatterns = [
    
   
    url(r'^paytm/payment/$', views.paytm_payment, name='paytm_payment'),
    url(r'^payment-response/$', views.paytm_response, name='paytm_response'),
    url(r'^guest_pay_at_host/$', views.guest_pay_at_host, name='guest_pay_at_host'),
    url('^listings/(?P<pk>[0-9]+)/details', views.guest_listing_detail, name='guest_listing_detail'),
    url('^listings/area/(?P<pk>[0-9]+)/details', views.guest_area_listings, name='guest_area_listings'),
    url('^listings/', views.guest_search_listings_view, name='guest_search_listings_view'),
    # url('^listings/', views.listings_view, name='listings_view'),
    url('login/', views.guest_login_view, name='guest_login_view'),
    url('signup/', views.guest_signup_view, name='guest_signup_view'),
    url('logout/', views.guest_logout_view, name='guest_logout_view'),
    # url('payment/success/', views.guest_payment_success, name='guest_payment_success_view'),
    # url('payment/failure/', views.guest_payment_failure, name='guest_payment_failure_view'),      
    # url('payment/', views.guest_payment_view, name='guest_payment_view'),  
    url('^my-bookings/(?P<pk>[0-9]+)/cancel/', views.guest_cancel_booking,name='guest_cancel_booking'),
    url('^my-bookings/$', views.guest_bookings,name='guest_bookings'),


    url('^$', views.guest_listings_home, name='guest_listings_home'),


    # url(r'^home/',views.Home),
    # url(r'^Success/',views.success),
    # url(r'^Failure/',views.failure),
       
]

host/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from host import views


urlpatterns = [
    
    url('registration/', views.host_creation_view, name='host_creation_view'),
    url('host_thank_you_view/', views.host_thank_you_view, name='host_thank_you_view'),
    url('login/', views.host_login_view, name='host_login_view'),
    url('logout/', views.host_logout_view, name='host_logout_view'),    
    url('my-listings/add-new-listing/', views.host_new_listing_view, name='host_new_listing_view'),
    url('my-listings/(?P<pk>[0-9]+)/$', views.host_listing_detail_view, name='host_listing_detail_view'),
    url('my-listings/$', views.host_listing_lists_view, name='host_listing_lists_view'),
    url('update/my-listing/(?P<pk>[0-9]+)/$', views.host_listing_update_view, name='host_listing_update_view'),
    url('my-listings/(?P<pk>[0-9]+)/add_new_bed/$', views.host_add_new_bed, name='host_add_new_bed'),
    url('my-listings/update_bed/$', views.host_bed_update_view, name='host_bed_update_view'),
    url('mylistings/bed/<int:pk>/$', views.host_bed_detail_view, name='host_bed_detail_view'),
    url('my-listings/beds/$', views.host_beds_list_view, name='host_beds_list_view'),
    url('my-dashboard/$', views.host_dashboard, name='host_dashboard'),
    url('my-dashboard/live_bookings/$', views.host_current_bookings, name='host_current_bookings'),
    url('my-listings/(?P<pk>[0-9]+)/stop_accepting_bookings/', views.stop_accepting_bookings, name='stop_accepting_bookings'),
    url('my-listings/(?P<pk>[0-9]+)/start_accepting_bookings/', views.start_accepting_bookings, name='start_accepting_bookings'),
    url('my-listings/(?P<pk>[0-9]+)/host_add_galary_images/', views.host_add_galary_images, name='host_add_galary_images'),
    url('my_profile/(?P<pk>[0-9]+)/update/', views.host_update_profile, name='host_update_profile'),
    url('my_profile/', views.host_profile, name='host_profile'),
    url('my_bank_details', views.add_host_bank_details, name='add_host_bank_details'),
    url('contact-us', views.host_contact_us, name='host_contact_us'),


    url('host_accpect_guest_checkin/(?P<pk>[0-9]+)/done', views.host_accpect_guest_checkin, name='host_accpect_guest_checkin'),
    url('host_checkout_guest/(?P<pk>[0-9]+)/done', views.host_checkout_guest, name='host_checkout_guest'),
    url('host_past_bookings/', views.host_past_bookings, name='host_past_bookings'),

    url('host_close_bed_bookings/(?P<pk>[0-9]+)/done', views.host_close_bed_bookings, name='host_close_bed_bookings'),
    url('host_open_bed_bookings/(?P<pk>[0-9]+)/done', views.host_open_bed_bookings, name='host_open_bed_bookings'),


    url('host_add_timings/(?P<pk>[0-9]+)/done', views.host_add_timings, name='host_add_timings'),
    url('host_update_timings/(?P<pk>[0-9]+)/done', views.host_update_timings, name='host_update_timings'),

]

soyobnb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include
from host.utils  import user_check
from django.views.generic import TemplateView

urlpatterns = [
    
    url('admin/', admin.site.urls),
    url('host/', include('host.urls')),
	url('user_check', user_check, name='user_check'),
	url('', include('guest.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest/models.py
import random
import string
import datetime
import pytz
from django.db import models
from django.contrib.auth.models import User
from host.models import Listing,Bed


class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True

class Guest(TimeStamp):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=150)
	last_name = models.CharField(max_length=150)
	email_id = models.EmailField(max_length=200)
	contact_number = models.CharField(max_length=250)
	profile_photo = models.ImageField(upload_to='guests/profile_photos', null=True, blank=True)
	
	def __str__(self):
		return "{} {}".format(self.first_name,self.last_name)
	
	@property
	def get_full_name(self):
		return self.first_name+self.last_name

	def send_welcome_email(self):
		pass


class Booking(TimeStamp):
	P_SOYO = 'soyo'
	P_HOST = 'host'
	primary_person = models.ForeignKey(User, on_delete=models.CASCADE)
	booking_date = models.DateField()
	booking_from = models.TimeField()
	booking_to = models.TimeField()
	number_of_guests = models.PositiveIntegerField()
	booking_id_num = models.CharField(max_length=15)
	is_amount_paid = models.BooleanField(default=False)
	total_amount = models.DecimalField(max_digits=10, decimal_places=2)
	booking_bed = models.CharField(max_length=255)
	booking_listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
	is_checkin = models.BooleanField(default=False)
	is_checkout = models.BooleanField(default=False)
	is_cancel = models.BooleanField(default=False)
	guest_cancled = models.BooleanField(default=False)
	guest_cancled_at = models.DateTimeField(null=True, blank=True)
	host_cancled_at = models.DateTimeField(null=True, blank=True)
	host_cancled = models.BooleanField(default=False)
	payment_type = models.CharField(max_length=10, null=True, blank=True)
	is_guest_reviewed = models.BooleanField(default=False)

	def __str__(self):
		return '{} booked {}'.format(str(self.primary_person), str(self.booking_listing))

	def cancle_booking_guest(self):
		self.is_cancel = True
		self.guest_cancled = True
		self.save(update_fields=['is_cancel', 'guest_cancled'])

	def cancel_booking_host(self):
		self.host_cancled = True
		tx = pytz.timezone('Asia/Kolkata')
		self.host_cancled_at = datetime.datetime.now(tz)
		self.save(update_fields=['host_cancled', 'host_cancled_at'])
		
	def get_booking_id(self):
		sl = 8
		letters=string.ascii_lowercase
		s = ''.join(random.choice(letters) for x in range(sl))
		return s

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		self.booking_id = self.get_booking_id()

	def host_accept_checkin(self):
		self.is_checkin = True
		self.is_amount_paid = True
		self.save(update_fields=['is_checkin', 'is_amount_paid'])

	def host_checkout(self):
		self.is_checkout = True
		self.save(update_fields=['is_checkout'])

	@property
	def get_total_hours(self):
		return self.booking_to - self.booking_from

	@property
	def get_booking_hours_human_format(self):
		return '{} to {}'.format(self.booking_from, self.booking_to)


	def send_confirmation_email_to_guest(self):
		pass

	def send_confirmation_email_to_host(self):
		pass

	def send_invoice_to_guest(self):
		pass

	def send_guest_reminder(self):
		pass

	def send_feedback_form_request(self):
		pass


class Rating(TimeStamp):
	listing = models.ForeignKey(Listing, on_delete=models.CASCADE,related_name='ratings')
	cleanness_rating = models.PositiveIntegerField(null=True,blank=True)
	service_rating = models.PositiveIntegerField(null=True,blank=True)
	staff_rating = models.PositiveIntegerField(null=True,blank=True)
	total_avg_rating = models.PositiveIntegerField(null=True, blank=True)
	guest = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return '{}-{}'.format(str(self.listing), str(self.guest))


from django.conf import settings
from django.utils import timezone

class Payment(TimeStamp):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='payments', on_delete=models.CASCADE)
	ORDERID = models.CharField('ORDER ID', max_length=50)
	TXNDATE = models.DateTimeField('TXN DATE', default=timezone.now)
	TXNID = models.IntegerField('TXN ID')
	BANKTXNID = models.IntegerField('BANK TXN ID', null=True, blank=True)
	BANKNAME = models.CharField('BANK NAME', max_length=100, null=True, blank=True)
	RESPCODE = models.IntegerField('RESP CODE')
	PAYMENTMODE = models.CharField('PAYMENT MODE', max_length=25, null=True, blank=True)
	CURRENCY = models.CharField('CURRENCY', max_length=4, null=True, blank=True)
	GATEWAYNAME = models.CharField('GATEWAY NAME', max_length=50, null=True, blank=True)
	MID = models.CharField(max_length=50)
	RESPMSG = models.TextField('RESP MSG', max_length=250)
	TXNAMOUNT = models.FloatField('TXN AMOUNT')
	STATUS =  models.CharField('STATUS', max_length=25)

	def __str__(self):
		return '{}-{}'.format(str(self.user), self.STATUS)	

guest/forms.py
from django import forms
from guest.models import Guest
from host.models import Area,Listing,Bed
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class GuestSignupForm(forms.Form):
	password = forms.CharField()
	first_name = forms.CharField()
	last_name = forms.CharField()
	email_id = forms.CharField()
	mobile_number = forms.CharField()

	class Meta:
		labels = {
			'username': _("UserName"),
			'password': _("Password"),
			'first_name': _("First Name"),
			'last_name': _("Last Name"),
			'email_id': _("Email Id"),
			'mobile_number': _("Mobile Number"),
		}
	
	
	def clean_username(self):
		un = self.cleaned_data.get('username')
		un_check = User.objects.filter(username=un).exists()
		if un_check:
			raise forms.ValidationError(
				self.error_messages['invalid_username'],
				code='invalid_username',
			)
		return un

	def clean_email(self):
		email = self.cleaned_data.get('email_id')
		check = Guest.objects.filter(email_id=email).exists()
		if check:
			raise forms.ValidationError(
				self.error_messages['invalid_email_id'],
				code='invalid_email_id',
			)
		return email


class BookingForm(forms.Form):
	
	error_messages = {
		'bed_is_not_available': 'Please Choose Another Bed',
		'invalid_number_of_guests': 'Please Enter Valid Number of Guests',
	}

	booking_bed = forms.CharField()
	number_of_guests = forms.IntegerField()
	booking_date = forms.DateField()
	booking_from = forms.TimeField()
	booking_to = forms.TimeField()

	def clean_booking_bed(self):
		bed = self.cleaned_data['booking_bed']
		# b_from = self.cleaned_data['booking_from']
		# b_to = self.cleaned_data['booking_to']
		bed_check = Bed.objects.get(title=bed)
		# booking_check = Booking.objects.filter(booking_bed=bed, booking_from=b_from, b_to=b_to).exists
		if bed_check.available_beds <=0:
			raise forms.ValidationError(
				self.error_messages['bed_is_not_available'],
				code='bed_is_not_available',
			)
		# if booking_check:
		# 	raise forms.ValidationError(
		# 		self.error_messages['bed_is_not_available'],
		# 		code='bed_is_not_available',
		# 	)
		return bed

	def clean_number_of_guests(self):
		ng = self.cleaned_data['number_of_guests']
		if int(ng) <= 0:
			raise forms.ValidationError(
				self.error_messages['invalid_number_of_guests'],
				code='invalid_number_of_guests',
			)
		return ng

	def clean_booking_date(self):
		b_date = self.cleaned_data['booking_date']
		print(b_date)
		return b_date


class SearchForm(forms.Form):
	areas = Area.objects.values('area_name')
	AREA_CHOICES = [area['area_name'] for area in areas]
	LISTING_TPYES = (
	    ('Hotel', 'Hotel'),
        ('Paying Guest', 'Paying Guest'),
        ('Shared House', 'Shared House')
    )
	# search_area = forms.ChoiceField(choices=AREA_CHOICES, label='', initial='',widget=forms.Select(), required=True)
	# search_type = forms.ChoiceField(choices=LISTING_TPYES, label='', initial='', widget=forms.Select(), required=False)
	checkin_date = forms.DateField(required=True, label='')
	chekin_time = forms.TimeField(required=True, label='')
	check_out_time = forms.TimeField(required=True, label='')



class RatingForm(forms.Form):
	RATING_CHOICES = [
		('1', '1'),
		('2', '2'),
		('3', '3'),
		('4', '4'),
		('5', '5'),
	]
	cleanness_rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect)
	service_rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect)
	staff_rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect)

	

templates/guest/Failure.html
<html>
<body>
<div style="display:none">
   	<input type="hidden" name="csrfmiddlewaretoken" value="{% csrf_token %}">
</div>
<h2>transaction failed</h2>
</body>
</html>

templates/guest/current_datetime.html
<html>
  <head onload="submitPayuForm()">
  <script type="text/javascript">
    var hash = "{{ hashh }}";
    function submitPayuForm() {
      if(hash =='') {
        return;
      }
      var payuForm = document.forms.payuForm;
      payuForm.submit();
    }
  </script>
  </head>
  <body>
    <h2>PayU Form</h2>
    <br/>
    {% if error %}
	
      <span style="color:red">Please fill all mandatory fields.</span>
      <br/>
      <br/>
      {% endif %}
      <form action="{{ action }}" method="post" name="payuForm">
        {% csrf_token %}
      <input type="hidden" name="key" value="{{ MERCHANT_KEY }}" />
      <input type="hidden" name="hash_string" value="{{ hash_string }}" />
      <input type="hidden" name="hash" value="{{ hashh }}"/>
       <input type="hidden" name="posted" value="{{ posted }}"/>
      <input type="hidden" name="txnid" value="{{ txnid }}" />
      <table>
        <tr>
          <td><b>Mandatory Parameters</b></td>
        </tr>
        <tr>
         <td>Amount: </td>
          <td><input name="amount" value="{{ posted.amount|default:'' }}" /></td>
          <td>First Name: </td>
          <td><input name="firstname" id="firstname" value="{{ posted.firstname|default:'' }}" /></td>
        </tr>
        <tr>
          <td>Email: </td>
          <td><input name="email" id="email" value="{{ posted.email|default:'' }}" /></td>
          <td>Phone: </td>
          <td><input name="phone" value="{{ posted.phone|default:'' }}" /></td>
        </tr>
        <tr>
          <td>Product Info: </td>
          <td colspan="3"><textarea name="productinfo">{{ posted.productinfo|default:'' }}</textarea></td>
        </tr>
        <tr>
          <td>Success URI: </td>
          <td colspan="3"><input name="surl" value="{{ posted.surl }}" size="64" /></td>
        </tr>
        <tr>
          <td>Failure URI: </td>
          <td colspan="3"><input name="furl" value="{{ posted.furl }}" size="64" /></td>
        </tr>

        <tr>
          <td colspan="3"><input type="hidden" name="service_provider" value="payu_paisa" size="64" /></td>
        
     <td colspan="4"><input type="submit" value="Submit" /></td>
      
    
        </tr>
      </table>
    </form>
  </body>
</html>

templates/guest/guest_bookings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SoyoBnB</title>
  <link href="https://fonts.googleapis.com/css?family=Cabin:400,600" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'assets/styles/style.css' %}">
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://efrolicss.com/assets/css/dist/efrolic.min.css">  
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <style type="text/css">
    .text-danger{
      color: #f44336;
    }
    .area_photo{
      width: 100%;
      height: 100%;
    }
    .text_white{
      color: #ffffff;
    }
    .text-green{
      color: #1B5E20;
    }
    .bg-soyo{
      background-color: red;
      color: white;
    }
  </style>    
</head>

<body>
{% include 'guest/guest_header.html' %} 
<section class="category-container page-section bg-wild-sand category--layout-1">
  <div class="container">
    <h2 class="page-section__title t-center">My Bookings</h2><br>
    <div class="row">
        {% for booking in upcoming_bookings %}
        <div class="col-lg-12 e-box">
            <div class="row">
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="border-right: 1px solid #f0f0f0;">
                Hotel: &nbsp;{{booking.booking_listing}}<br>
                Id : &nbsp;{{booking.booking_id_num}}
              </div>              
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="border-right: 1px solid #f0f0f0;">
                Date:&nbsp;{{booking.booking_date}}<br/>
                Checkin:&nbsp;{{booking.booking_from}}<br/>
                Checkout:&nbsp;{{booking.booking_to}}
              </div>
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="border-right: 1px solid #f0f0f0;">
                 <a href="{% url 'guest_cancel_booking' booking.pk %}" class="e-btn plane danger" style="text-decoration: none;"> Cancel Booking</a>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="border-right: 1px solid #f0f0f0;">
                  <a href="" class="e-btn plain info" style="text-decoration: none;">Get Assistance</a>
              </div>              
            </div>           
        </div>      
        {% endfor %}
    </div><!-- .row -->

    <div class="row">
        <div class="col-lg-12">
          Cancel Bookings
        </div>
        {% for booking in cancled_bookings %}
        <div class="col-lg-12 e-box">
            <div class="row">
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="border-right: 1px solid #f0f0f0;">
                Hotel: &nbsp;{{booking.booking_listing}}<br>
                Id : &nbsp;{{booking.id}}
              </div>              
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="border-right: 1px solid #f0f0f0;">
                Date:&nbsp;{{booking.booking_date}}<br/>
                Checkin:&nbsp;{{booking.booking_from}}<br/>
                Checkout:&nbsp;{{booking.booking_to}}
              </div>
                          
            </div>           
        </div>      
        {% endfor %}
    </div><!-- .row -->    
  </div><!-- .container -->
</section><!-- .category -->

{% include 'guest/guest_footer.html' %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDyCxHyc8z9gMA5IlipXpt0c33Ajzqix4"></script>
<script src="https://cdn.rawgit.com/googlemaps/v3-utility-library/master/infobox/src/infobox.js"></script>
<script src="{% static 'assets/scripts/app.js' %}"></script>
</body>
</html>

templates/guest/guest_payment_failure.html
Payment failure

templates/guest/listings (copy).html
{% extends 'base.html' %}

templates/guest/signup.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
	<title>SoyoBnB</title>
	<link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" />
  	<script src="https://kit.fontawesome.com/a076d05399.js"></script>
  	<style type="text/css">
  		.login_btn{
  			background-color: #e65100;
  			color:#fff;
  		}
  		.signup_btn{
  			color: #e65100;
  		}
  		.login_box{

  		}
      a:hover{
        text-decoration: none;
      }
  		html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: -webkit-box;
  display: flex;
  -ms-flex-align: center;
  -ms-flex-pack: center;
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

  	</style>

</head>
<body class="text-center">
    <form class="form-signin" method="post">
    	{% csrf_token %}
      <!-- <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72"> -->
                         {% csrf_token %}
                            <div class="form-group">
                                            <input 
                                                   type="text" 
                                                   class="form-control {% if form.first_name.errors %} is-invalid {% endif %}"
                                                   id="id_first_name"
                                                   name="first_name"
                                                   placeholder="Enter First Name"
                                                   value="{{form.first_name.value|default:''}}"
                                                   />
                                            {% if form.first_name.errors %}
                                                <div class="invalid-feedback">
                                                    {{form.first_name.errors}}
                                                </div>
                                            {% endif %}

                            </div>    

                             <div class="form-group">
                                            <input 
                                                   type="text" 
                                                   class="form-control {% if form.last_name.errors %} is-invalid {% endif %}"
                                                   id="id_last_name"
                                                   name="last_name"
                                                   placeholder="Enter Last Name"
                                                   value="{{form.last_name.value|default:''}}"
                                                   />
                                            {% if form.last_name.errors %}
                                                <div class="invalid-feedback">
                                                    {{form.last_name.errors}}
                                                </div>
                                            {% endif %}

                            </div>
                            <div class="form-group">
                                            <input 
                                                   type="email" 
                                                   class="form-control {% if form.email_id.errors %} is-invalid {% endif %}"
                                                   id="id_email_id"
                                                   name="email_id"
                                                   placeholder="Enter Email Address"
                                                   value="{{form.email_id.value|default:''}}"
                                                   />
                                            {% if form.email.errors %}
                                                <div class="invalid-feedback">
                                                    {{form.email.errors}}
                                                </div>
                                            {% endif %}

                            </div>                        
                            <div class="form-group">
                                            <input 
                                                   type="text" 
                                                   class="form-control {% if form.mobile_number.errors %} is-invalid {% endif %}"
                                                   id="id_mobile_number"
                                                   name="mobile_number"
                                                   placeholder="Enter Mobile Number"
                                                   value="{{form.mobile_number.value|default:''}}"
                                                   />
                                            {% if form.mobile_number.errors %}
                                                <div class="invalid-feedback">
                                                    {{form.mobile_number.errors}}
                                                </div>
                                            {% endif %}

                            </div>                             

                                        <div class="form-group">
                                            <input 
                                                   type="password" 
                                                   class="form-control {% if form.password.errors %} is-invalid {% endif %}"
                                                   id="id_password"
                                                   name="password"
                                                   placeholder="Enter Password"
                                                   value="{{form.password.value|default:''}}"
                                                   />
                                            {% if form.password.errors %}
                                                <div class="invalid-feedback">
                                                    {{form.password.errors}}
                                                </div>
                                            {% endif %}

                                        </div>
      <button class="btn btn-lg login_btn btn-block" type="submit">Signup</button><br>
      Already Have an Account <a class="signup_btn" href="{% url 'guest_login_view' %}"><span style="color: green">Login Here</span></a>
      <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
    </form>
  </body>
</html>

templates/guest/sucess.html
<html>
<body>
<div style="display:none">
   	<input type="hidden" name="csrfmiddlewaretoken" value="{% csrf_token %}">
</div>
<h4>Thank You.</h4>
<h4>Your order status is {{ status }}</h4>
<h4>Your Transaction ID for this transaction is {{ txnid }}</h4>
<h4>We have received a payment of Rs {{ amount}}</h4> 

</body>
</html>